"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "EN" | "RU"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  EN: {
    // Navigation
    "nav.home": "Home",
    "nav.modules": "Modules",
    "nav.progress": "Progress",
    "nav.achievements": "Achievements",
    "nav.finalExam": "Final Exam",
    "nav.admin": "Admin",
    "nav.adminDashboard": "Admin Dashboard",
    "nav.manageStudents": "Manage Students",
    "nav.manageModules": "Manage Modules",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.signUp": "Sign Up",
    "nav.level": "Level",

    // Home page
    "home.title": "Keele Seiklus",
    "home.description":
      "Master Estonian through an immersive journey across 40 beautiful destinations. Experience authentic culture, master practical vocabulary, and earn your certificate.",
    "home.interactiveModules": "Interactive Modules",
    "home.hoursContent": "Hours of Content",
    "home.officialCert": "Official Certificate",
    "home.culturalImmersion": "Cultural Immersion",
    "home.continueLearning": "Continue Learning",
    "home.viewProgress": "View Progress",
    "home.startJourney": "Start Your Journey",
    "home.exploreFreeModules": "Explore Free Modules",
    "home.welcomeBack": "Welcome back,",
    "home.completedModules": "You've completed",
    "home.ofModules": "of",
    "home.modules": "modules",
    "home.startEstonianAdventure": "Start Your Estonian Adventure",
    "home.beginWithFree": "Begin with our free introductory modules and experience the journey",
    "home.free": "FREE",
    "home.reviewModule": "Review Module",
    "home.startFreeModuleBtn": "Start Free Module",
    "home.viewAllModules": "View All",
    "home.whyChoose": "Why Choose Keele Seiklus?",
    "home.comprehensiveApproach": "Our comprehensive approach combines storytelling, culture, and practical skills",
    "home.interactiveLearning": "Interactive Learning",
    "home.interactiveLearningDesc": "Engage with stories, exercises, and real-world scenarios",
    "home.culturalImmersionTitle": "Cultural Immersion",
    "home.culturalImmersionDesc": "Experience Estonian culture through virtual destinations",
    "home.achievementSystem": "Achievement System",
    "home.achievementSystemDesc": "Track progress with badges, certificates, and milestones",
    "home.certificationTitle": "Official Certification",
    "home.certificationDesc": "Earn recognized certificates for your achievements",
    "home.readyToLearnMore": "Ready to Learn More?",
    "home.joinThousands": "Join thousands of learners mastering Estonian with our proven method",
    "home.contactUs": "Contact Us",
    "home.getInTouch": "Get in Touch",
    "home.contactDescription":
      "Have questions about learning Estonian? We're here to help you on your language journey.",
    "home.sendMessage": "Send us a Message",

    // Contact page
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions about learning Estonian? We're here to help you on your language journey.",
    "contact.getInTouch": "Get in Touch",
    "contact.getInTouchDesc": "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.faq": "Frequently Asked Questions",
    "contact.faqQuestion1": "How long does it take to learn Estonian?",
    "contact.faqAnswer1": "With our structured approach, most students achieve conversational level in 6-12 months.",
    "contact.faqQuestion2": "Are the first modules really free?",
    "contact.faqAnswer2": "Yes! The first 3 modules are completely free with no registration required.",
    "contact.faqQuestion3": "Do I get a certificate?",
    "contact.faqAnswer3": "Yes, you'll receive an official certificate upon completing all 40 modules.",
    "contact.sendMessage": "Send us a Message",
    "contact.sendMessageDesc": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.name": "Name",
    "contact.nameRequired": "Name *",
    "contact.namePlaceholder": "Your full name",
    "contact.emailRequired": "Email *",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.subject": "Subject",
    "contact.subjectRequired": "Subject *",
    "contact.subjectPlaceholder": "What is this about?",
    "contact.message": "Message",
    "contact.messageRequired": "Message *",
    "contact.messagePlaceholder": "Tell us more about your question or feedback...",
    "contact.sending": "Sending...",
    "contact.sendButton": "Send Message",
    "contact.messageSent": "Message Sent!",
    "contact.thankYou": "Thank you for contacting us. We'll get back to you within 24 hours.",
    "contact.redirecting": "Redirecting back to form...",

    // Login page
    "login.yourEstonianAdventure": "Your Estonian Adventure Awaits",
    "login.welcomeBack": "Welcome Back",
    "login.joinAdventure": "Join the Adventure",
    "login.continueJourney": "Continue your language learning journey",
    "login.startEstonianAdventure": "Start your Estonian adventure today",
    "login.fullName": "Full Name",
    "login.enterFullName": "Enter your full name",
    "login.email": "Email Address",
    "login.enterEmail": "Enter your email address",
    "login.password": "Password",
    "login.enterPassword": "Enter your password",
    "login.confirmPassword": "Confirm Password",
    "login.confirmPasswordPlaceholder": "Confirm your password",
    "login.agreeToTerms": "I agree to the",
    "login.termsOfService": "Terms of Service",
    "login.and": "and",
    "login.privacyPolicy": "Privacy Policy",
    "login.signingIn": "Signing in...",
    "login.signIn": "Sign In",
    "login.createAccount": "Create Account",
    "login.forgotPassword": "Forgot your password?",
    "login.dontHaveAccount": "Don't have an account? Sign up",
    "login.alreadyHaveAccount": "Already have an account? Sign in",
    "login.adminAccess": "Admin Access",
    "login.testBrowserStorage": "Test Browser Storage",
    "login.whatYoullLearn": "What You'll Learn",
    "login.interactiveModules": "40 Interactive Modules",
    "login.estonianDestinations": "Estonian Destinations",
    "login.achievementsBadges": "Achievements & Badges",
    "login.certification": "Official Certification",

    // Modules page
    "modules.title": "Learning Modules",
    "modules.welcomeBack": "Welcome back,",
    "modules.continueJourney": "Continue your Estonian learning journey",
    "modules.exploreModules": "Explore our comprehensive Estonian learning modules",
    "modules.completed": "Completed",
    "modules.totalModules": "Total Modules",
    "modules.progress": "Progress",
    "modules.level": "Level",
    "modules.overallProgress": "Overall Progress",
    "modules.modulesCompleted": "modules completed",
    "modules.freeAccessAvailable": "Free Access Available",
    "modules.tryModulesFree": "Try our first 3 modules free - no registration required!",
    "modules.loginToUnlockAll": "Login to Unlock More",
    "modules.levelLabel": "Level",
    "modules.duration": "Duration",
    "modules.completedStatus": "Completed",
    "modules.freeAccess": "Free Access",
    "modules.available": "Available",
    "modules.loginRequired": "Login Required",
    "modules.locked": "Locked",
    "modules.free": "FREE",
    "modules.readyToLearnMore": "Ready to Learn More?",
    "modules.joinThousands": "Join thousands of learners mastering Estonian",
    "modules.loginNow": "Login Now",
    "modules.tryFreeModule": "Try Free Module",

    // Module page
   
    "module.backToModules": "Back to Modules",
     "module.progress": "Progress",
     
     "module.takeQuiz": "Take Quiz",
    "module.loadingModule": "Loading module...",
    "module.moduleNotFound": "Module Not Found",
    "module.moduleNotFoundDesc": "The requested module could not be found.",
    "module.moduleLocked": "Module Locked",
    "module.moduleLockedDesc": "Please complete previous modules to unlock this one.",
    "module.loginToAccess": "Login to Access",
    "module.interactiveVideoStory": "Interactive Video Story",
    "module.experienceAuthentic": "Experience authentic Estonian conversations",
    "module.story": "Story",
    "module.vocabulary": "Vocabulary",
    "module.grammar": "Grammar",
    "module.pronunciation": "Pronunciation",
    "module.listening": "Listening",
    "module.speaking": "Speaking",
    "module.reading": "Reading",
    "module.writing": "Writing",
    "module.cultural": "Cultural",
    "module.yourMission": "Your Mission",
    "module.storyTranscript": "Story Transcript",
    "module.showTranslation": "Show Translation",
    "module.learningHint": "Learning Hint",
    "module.completeContinue": "Complete & Continue",
    "module.sectionComplete": "Section Complete",
    "module.quickActions": "Quick Actions",
    "module.playModuleAudio": "Play Module Audio",
    "module.downloadPDF": "Download PDF",
    "module.joinDiscussion": "Join Discussion",
    "module.culturalSouvenir": "Cultural Souvenir",
    "module.downloadSouvenir": "Download Souvenir",
    "module.previousModule": "Previous Module",
    "module.markSectionComplete": "Mark Section Complete",
    "module.nextModule": "Next Module",
    "module.learnEssential": "Learn essential vocabulary for this module",
    "module.noVocabulary": "No vocabulary items available for this module",
    "module.previousStory": "Previous: Story",
    "module.markAsComplete": "Mark as Complete",
    "module.nextGrammar": "Next: Grammar",
    "module.masterGrammar": "Master the grammar structures",
    "module.grammarRules": "Grammar Rules",
    "module.examples": "Examples",
    "module.practiceExercises": "Practice Exercises",
    "module.previousVocabulary": "Previous: Vocabulary",
    "module.nextPronunciation": "Next: Pronunciation",
    "module.masterPronunciation": "Master proper pronunciation",
    "module.focusAreas": "Focus Areas",
    "module.pronunciationExercises": "Pronunciation Exercises",
    "module.minimalPairs": "Minimal Pairs",
    "module.previousGrammar": "Previous: Grammar",
    "module.nextListening": "Next: Listening",
    "module.practiceUnderstanding": "Practice understanding spoken Estonian",
    "module.playAudioDialogue": "Play Audio Dialogue",
    "module.listenCarefully": "Listen carefully and follow along",
    "module.listenToAudio": "Listen to Audio",
    "module.transcript": "Transcript",
    "module.comprehensionQuestions": "Comprehension Questions",
    "module.previousPronunciation": "Previous: Pronunciation",
    "module.nextSpeaking": "Next: Speaking",
    "module.practicePronunciation": "Practice speaking Estonian",
    "module.speakingExercises": "Speaking Exercises",
    "module.prompt": "Prompt:",
    "module.expectedResponse": "Expected Response:",
    "module.startRecording": "Start Recording",
    "module.previousListening": "Previous: Listening",
    "module.nextReading": "Next: Reading",
    "module.readAndUnderstand": "Read and understand Estonian texts",
    "module.readingText": "Reading Text",
    "module.previousSpeaking": "Previous: Speaking",
    "module.nextWriting": "Next: Writing",
    "module.writingPractice": "Practice writing in Estonian",
    "module.writingExercises": "Writing Exercises",
    "module.hints": "Hints:",
    "module.writeResponse": "Write your response here...",
    "module.submitWriting": "Submit Writing",
    "module.previousReading": "Previous: Reading",
    "module.nextCulture": "Next: Culture",
    "module.culturalNote": "Discover Estonian culture and traditions",
    "module.digitalSouvenir": "Digital Souvenir:",
    "module.previousWriting": "Previous: Writing",
    "module.congratulations": "Congratulations!",
    "module.completedAllSections": "You've completed all sections of this module",
    "module.takeFinalQuiz": "Take Final Quiz",

    // Progress page
    "progress.modulesCompleted": "Modules Completed",
    "progress.ofTotal": "of",
    "progress.loadingProgress": "Loading your progress...",
    "progress.loginRequired": "Login Required",
    "progress.loginRequiredDesc": "Please log in to view your learning progress.",
    "progress.title": "Your Learning Progress",
    "progress.welcomeNewUser": "Start your Estonian learning journey today.",
    "progress.welcomeReturning": "Keep up the excellent work.",
    "progress.overallProgress": "Overall Progress",
    "progress.completionRate": "completion rate",
    "progress.studyTime": "Study Time",
    "progress.totalHours": "total hours",
    "progress.currentStreak": "Current Streak",
    "progress.daysActive": "days active",
    "progress.overallCourseProgress": "Overall Course Progress",
    "progress.modulesRemaining": "modules remaining",
    "progress.nextMilestone": "Next Milestone",
    "progress.moduleProgress": "Module Progress",
    "progress.progress": "Progress",
    "progress.review": "Review",
    "progress.continue": "Continue",
    "progress.start": "Start",
    "progress.viewAllModules": "View All {total} Modules",
    "progress.startLearning": "Start Learning",
    "progress.continueLearning": "Continue Learning",
    "progress.beginJourney": "Begin your Estonian journey with Module 1",
    "progress.pickUpWhereLeft": "Pick up where you left off",
    "progress.startNow": "Start Now",
    "progress.achievements": "Achievements",
    "progress.viewMilestones": "View your learning milestones and badges",
    "progress.viewAchievements": "View Achievements",
    "progress.detailedStats": "Detailed Stats",
    "progress.analyzePatterns": "Analyze your learning patterns and performance",
    "progress.comingSoon": "Coming Soon",
    "progress.milestones": {
      firstModule: "Complete your first module!",
      fiveModules: "Reach 5 modules to unlock achievements!",
      tenModules: "Complete 10 modules to earn your first certificate!",
      twentyModules: "Halfway to mastery - 20 modules!",
      allModules: "Complete all modules for the final certificate!",
      mastered: "Congratulations! You've mastered Estonian!",
    },

    // Achievements page
    "achievements.title": "Achievements",
    "achievements.description": "Track your learning milestones and unlock badges",
    "achievements.all": "All",
    "achievements.learning": "Learning",
    "achievements.progress": "Progress",
    "achievements.social": "Social",
    "achievements.special": "Special",
    "achievements.totalPoints": "Total Points",
    "achievements.dayStreak": "Day Streak",
    "achievements.modules": "Modules",
    "achievements.nextAchievement": "Next Achievement",
    "achievements.statistics": "Statistics",

    // Exam page
    "exam.title": "Final Examination",
    "exam.subtitle": "Test your Estonian language skills",
    "exam.locked": "Exam Locked",
    "exam.lockedDesc": "Complete {required} modules to unlock the final exam",
    "exam.complete": "Exam Complete",
    "exam.results": "Your Results",
    "exam.pointsEarned": "Points Earned",
    "exam.congratulations": "Congratulations!",
    "exam.passed": "You have successfully passed the Estonian language exam!",
    "exam.failed": "You need 70% or higher to pass. Keep studying and try again!",
    "exam.downloadCertificate": "Download Certificate",
    "exam.retakeExam": "Retake Exam",
    "exam.viewProgress": "View Progress",
    "exam.instructions": "Exam Instructions",
    "exam.totalPoints": "Total Points",
    "exam.hours": "Hours",
    "exam.toPass": "To Pass",
    "exam.sections": "Sections",
    "exam.startExam": "Start Exam",
    "exam.vocabulary": "Vocabulary (20 points)",
    "exam.grammar": "Grammar (20 points)",
    "exam.pronunciation": "Pronunciation (10 points)",
    "exam.listening": "Listening (15 points)",
    "exam.reading": "Reading (15 points)",
    "exam.cultural": "Cultural Knowledge (5 points)",

    // Payment page
    "payment.title": "Upgrade to Premium",
    "payment.subtitle": "Unlock all modules and earn your certificate",
    "payment.backToModules": "Back to Modules",
    "payment.moduleRequiresPremium": "requires Premium access.",
    "payment.upgradeNow": "Upgrade now to continue learning!",
    "payment.choosePlan": "Choose Your Plan",
    "payment.selectPlan": "Select the plan that works best for you",
    "payment.paymentMethod": "Payment Method",
    "payment.choosePayment": "Choose your preferred payment method",
    "payment.emailAddress": "Email Address",
    "payment.emailPlaceholder": "Enter your email address",
    "payment.cardNumber": "Card Number",
    "payment.cardPlaceholder": "1234 5678 9012 3456",
    "payment.expiryDate": "Expiry Date",
    "payment.expiryPlaceholder": "MM/YY",
    "payment.cvv": "CVV",
    "payment.cvvPlaceholder": "123",
    "payment.cardholderName": "Cardholder Name",
    "payment.cardholderPlaceholder": "Full name on card",
    "payment.orderSummary": "Order Summary",
    "payment.total": "Total",
    "payment.acceptTerms": "I accept the",
    "payment.termsOfService": "Terms of Service",
    "payment.and": "and",
    "payment.privacyPolicy": "Privacy Policy",
    "payment.processing": "Processing...",
    "payment.completePayment": "Complete Payment",
    "payment.securePayment": "Secure 256-bit SSL encryption",
    "payment.emailRequired": "Email is required",
    "payment.validEmail": "Please enter a valid email",
    "payment.cardRequired": "Card number is required",
    "payment.validCard": "Please enter a valid card number",
    "payment.expiryRequired": "Expiry date is required",
    "payment.validExpiry": "Please enter a valid expiry date (MM/YY)",
    "payment.cvvRequired": "CVV is required",
    "payment.validCvv": "Please enter a valid CVV",
    "payment.nameRequired": "Cardholder name is required",
    "payment.mustAcceptTerms": "You must accept the terms and conditions",
    "payment.processingFailed": "Payment processing failed. Please try again.",

    // Forgot Password page
    "forgotPassword.title": "Forgot Password",
    "forgotPassword.resetPassword": "Reset Your Password",
    "forgotPassword.enterEmail": "Enter your email address and we'll send you a reset link",
    "forgotPassword.emailAddress": "Email Address",
    "forgotPassword.enterEmailPlaceholder": "Enter your email address",
    "forgotPassword.sendResetEmail": "Send Reset Email",
    "forgotPassword.sendingResetEmail": "Sending Reset Email...",
    "forgotPassword.backToLogin": "Back to Login",
    "forgotPassword.needHelp": "Need Help?",
    "forgotPassword.helpText1": "Make sure you enter the correct email address",
    "forgotPassword.helpText2": "Check your spam folder if you don't see the email",
    "forgotPassword.helpText3": "Reset links expire after 1 hour for security",
    "forgotPassword.helpText4": "Contact support if you continue having issues",
    "forgotPassword.demoText": "This is a demo. No actual emails will be sent.",
    "forgotPassword.pleaseEnterEmail": "Please enter your email address",
    "forgotPassword.pleaseEnterValidEmail": "Please enter a valid email address",
    "forgotPassword.failedToSend": "Failed to send reset email. Please try again.",
    "forgotPassword.resetEmailSent": "Reset Email Sent",
    "forgotPassword.checkInbox": "Please check your email inbox for reset instructions",
    "forgotPassword.sentTo": "Email sent to:",
    "forgotPassword.important": "Important:",
    "forgotPassword.checkSpam": "Check your spam/junk folder",
    "forgotPassword.linkExpires": "Link expires in 1 hour",
    "forgotPassword.ignoreIfNotRequested": "Ignore this email if you didn't request it",
    "forgotPassword.sendAnotherEmail": "Send Another Email",
    "forgotPassword.stillTrouble": "Still having trouble?",
    "forgotPassword.demoMode": "In demo mode, password reset links lead to /reset-password?token=valid123",

    // Terms page
    "terms.backToLogin": "Back to Login",
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated: December 2024",
    "terms.returnToLogin": "Return to Login",

    // Privacy page
    "privacy.backToLogin": "Back to Login",
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated: December 2024",
    "privacy.returnToLogin": "Return to Login",

    // Map section translations
    "map.yourEstonianAdventure": "Your Estonian Adventure",
    "map.trackProgress": "Track your progress across Estonia's beautiful destinations and celebrate your achievements.",
    "map.exploreDestinations":
      "Explore Estonia's beautiful destinations. Modules 1-3 are free! Login to unlock all modules and save your progress.",
    "map.exploreFreeDemo": "🗺️ Explore Estonia - Free Demo",
    "map.freeModulesDesc":
      "Modules 1-3 are completely free! Explore Tallinn, Tartu, and Saaremaa. Login to unlock all {count} destinations and track your progress.",
    "map.loginToUnlockAll": "Login to Unlock All",
    "map.destinationsVisited": "Destinations Visited",
    "map.freeDestinations": "Free Destinations",
    "map.overallProgress": "Overall Progress",
    "map.hoursContent": "Hours Content",
    "map.adventureMap": "Estonia Adventure Map ({count} destinations)",
    "map.clickDestinations": "Click on destinations to see your progress and continue your journey",
    "map.freeToExplore": "Modules 1-3 are free to explore! Login to unlock all destinations.",
    "map.loadingMap": "Loading map...",
    "map.mapLegend": "Map Legend",
    "map.completed": "Completed",
    "map.freeAccess": "Free Access",
    "map.available": "Available",
    "map.locked": "Locked",
    "map.loginToUnlock": "Login to Unlock",
    "map.completePrevious": "Complete previous modules to unlock",
    "map.reviewModule": "Review Module",
    "map.continue": "Continue",
    "map.startFreeModule": "Start Free Module",
    "map.startModule": "Start Module",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.loginToContinue": "Login to Continue",
  },
  RU: {
    // Navigation
    "nav.home": "Главная",
    "nav.modules": "Модули",
    "nav.progress": "Прогресс",
    "nav.achievements": "Достижения",
    "nav.finalExam": "Итоговый экзамен",
    "nav.admin": "Админ",
    "nav.adminDashboard": "Панель администратора",
    "nav.manageStudents": "Управление студентами",
    "nav.manageModules": "Управление модулями",
    "nav.login": "Войти",
    "nav.logout": "Выйти",
    "nav.signUp": "Регистрация",
    "nav.level": "Уровень",

    // Home page
    "home.title": "Keele Seiklus",
    "home.description":
      "Освойте эстонский язык через увлекательное путешествие по 40 красивым местам. Познакомьтесь с аутентичной культурой, изучите практическую лексику и получите сертификат.",
    "home.interactiveModules": "Интерактивные модули",
    "home.hoursContent": "Часов контента",
    "home.officialCert": "Официальный сертификат",
    "home.culturalImmersion": "Культурное погружение",
    "home.continueLearning": "Продолжить обучение",
    "home.viewProgress": "Посмотреть прогресс",
    "home.startJourney": "Начать путешествие",
    "home.exploreFreeModules": "Изучить бесплатные модули",
    "home.welcomeBack": "С возвращением,",
    "home.completedModules": "Вы завершили",
    "home.ofModules": "из",
    "home.modules": "модулей",
    "home.startEstonianAdventure": "Начните ваше эстонское приключение",
    "home.beginWithFree": "Начните с наших бесплатных вводных модулей и окунитесь в путешествие",
    "home.free": "БЕСПЛАТНО",
    "home.reviewModule": "Повторить модуль",
    "home.startFreeModuleBtn": "Начать бесплатный модуль",
    "home.viewAllModules": "Посмотреть все",
    "home.whyChoose": "Почему выбрать Keele Seiklus?",
    "home.comprehensiveApproach": "Наш комплексный подход объединяет повествование, культуру и практические навыки",
    "home.interactiveLearning": "Интерактивное обучение",
    "home.interactiveLearningDesc": "Взаимодействуйте с историями, упражнениями и реальными сценариями",
    "home.culturalImmersionTitle": "Культурное погружение",
    "home.culturalImmersionDesc": "Познакомьтесь с эстонской культурой через виртуальные путешествия",
    "home.achievementSystem": "Система достижений",
    "home.achievementSystemDesc": "Отслеживайте прогресс с помощью значков, сертификатов и вех",
    "home.certificationTitle": "Официальная сертификация",
    "home.certificationDesc": "Получайте признанные сертификаты за ваши достижения",
    "home.readyToLearnMore": "Готовы изучать больше?",
    "home.joinThousands": "Присоединяйтесь к тысячам учащихся, изучающих эстонский с нашим проверенным методом",
    "home.contactUs": "Связаться с нами",
    "home.getInTouch": "Связаться с нами",
    "home.contactDescription":
      "Есть вопросы об изучении эстонского языка? Мы здесь, чтобы помочь вам в вашем языковом путешествии.",
    "home.sendMessage": "Отправить нам сообщение",

    // Contact page
    "contact.title": "Связаться с нами",
    "contact.subtitle":
      "Есть вопросы об изучении эстонского языка? Мы здесь, чтобы помочь вам в вашем языковом путешествии.",
    "contact.getInTouch": "Связаться с нами",
    "contact.getInTouchDesc": "Мы будем рады услышать от вас. Отправьте нам сообщение, и мы ответим как можно скорее.",
    "contact.email": "Электронная почта",
    "contact.phone": "Телефон",
    "contact.address": "Адрес",
    "contact.faq": "Часто задаваемые вопросы",
    "contact.faqQuestion1": "Сколько времени нужно, чтобы выучить эстонский язык?",
    "contact.faqAnswer1":
      "С нашим структурированным подходом большинство студентов достигают разговорного уровня за 6-12 месяцев.",
    "contact.faqQuestion2": "Действительно ли первые модули бесплатны?",
    "contact.faqAnswer2": "Да! Первые 3 модуля полностью бесплатны и не требуют регистрации.",
    "contact.faqQuestion3": "Получу ли я сертификат?",
    "contact.faqAnswer3": "Да, вы получите официальный сертификат после завершения всех 40 модулей.",
    "contact.sendMessage": "Отправить нам сообщение",
    "contact.sendMessageDesc": "Заполните форму ниже, и мы свяжемся с вами как можно скорее.",
    "contact.name": "Имя",
    "contact.nameRequired": "Имя *",
    "contact.namePlaceholder": "Ваше полное имя",
    "contact.emailRequired": "Электронная почта *",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.subject": "Тема",
    "contact.subjectRequired": "Тема *",
    "contact.subjectPlaceholder": "О чем это?",
    "contact.message": "Сообщение",
    "contact.messageRequired": "Сообщение *",
    "contact.messagePlaceholder": "Расскажите нам больше о вашем вопросе или отзыве...",
    "contact.sending": "Отправка...",
    "contact.sendButton": "Отправить сообщение",
    "contact.messageSent": "Сообщение отправлено!",
    "contact.thankYou": "Спасибо, что связались с нами. Мы свяжемся с вами в течение 24 часов.",
    "contact.redirecting": "Перенаправление обратно к форме...",

    // Login page
    "login.yourEstonianAdventure": "Ваше эстонское приключение ждет",
    "login.welcomeBack": "С возвращением",
    "login.joinAdventure": "Присоединиться к приключению",
    "login.continueJourney": "Продолжите ваше путешествие в изучении языка",
    "login.startEstonianAdventure": "Начните ваше эстонское приключение сегодня",
    "login.fullName": "Полное имя",
    "login.enterFullName": "Введите ваше полное имя",
    "login.email": "Адрес электронной почты",
    "login.enterEmail": "Введите ваш адрес электронной почты",
    "login.password": "Пароль",
    "login.enterPassword": "Введите ваш пароль",
    "login.confirmPassword": "Подтвердите пароль",
    "login.confirmPasswordPlaceholder": "Подтвердите ваш пароль",
    "login.agreeToTerms": "Я согласен с",
    "login.termsOfService": "Условиями обслуживания",
    "login.and": "и",
    "login.privacyPolicy": "Политикой конфиденциальности",
    "login.signingIn": "Вход в систему...",
    "login.signIn": "Войти",
    "login.createAccount": "Создать аккаунт",
    "login.forgotPassword": "Забыли пароль?",
    "login.dontHaveAccount": "Нет аккаунта? Зарегистрируйтесь",
    "login.alreadyHaveAccount": "Уже есть аккаунт? Войдите",
    "login.adminAccess": "Доступ администратора",
    "login.testBrowserStorage": "Тест хранилища браузера",
    "login.whatYoullLearn": "Что вы изучите",
    "login.interactiveModules": "40 интерактивных модулей",
    "login.estonianDestinations": "Эстонские направления",
    "login.achievementsBadges": "Достижения и значки",
    "login.certification": "Официальная сертификация",

    // Modules page
    "modules.title": "Обучающие модули",
    "modules.welcomeBack": "С возвращением,",
    "modules.continueJourney": "Продолжите ваше путешествие в изучении эстонского языка",
    "modules.exploreModules": "Изучите наши комплексные модули изучения эстонского языка",
    "modules.completed": "Завершено",
    "modules.totalModules": "Всего модулей",
    "modules.progress": "Прогресс",
    "modules.level": "Уровень",
    "modules.overallProgress": "Общий прогресс",
    "modules.modulesCompleted": "модулей завершено",
    "modules.freeAccessAvailable": "Доступен бесплатный доступ",
    "modules.tryModulesFree": "Попробуйте наши первые 3 модуля бесплатно - регистрация не требуется!",
    "modules.loginToUnlockAll": "Войдите, чтобы разблокировать больше",
    "modules.levelLabel": "Уровень",
    "modules.duration": "Продолжительность",
    "modules.completedStatus": "Завершено",
    "modules.freeAccess": "Бесплатный доступ",
    "modules.available": "Доступно",
    "modules.loginRequired": "Требуется вход",
    "modules.locked": "Заблокировано",
    "modules.free": "БЕСПЛАТНО",
    "modules.readyToLearnMore": "Готовы изучать больше?",
    "modules.joinThousands": "Присоединяйтесь к тысячам учащихся, изучающих эстонский",
    "modules.loginNow": "Войти сейчас",
    "modules.tryFreeModule": "Попробовать бесплатный модуль",

    // Module page
    "module.loadingModule": "Загрузка модуля...",
    "module.moduleNotFound": "Модуль не найден",
    "module.moduleNotFoundDesc": "Запрашиваемый модуль не найден.",
    "module.moduleLocked": "Модуль заблокирован",
    "module.moduleLockedDesc": "Пожалуйста, завершите предыдущие модули, чтобы разблокировать этот.",
    "module.loginToAccess": "Войдите для доступа",
    "module.interactiveVideoStory": "Интерактивная видео-история",
    "module.experienceAuthentic": "Познакомьтесь с аутентичными эстонскими разговорами",
    "module.story": "История",
    "module.vocabulary": "Лексика",
    "module.grammar": "Грамматика",
    "module.pronunciation": "Произношение",
    "module.listening": "Аудирование",
    "module.speaking": "Говорение",
    "module.reading": "Чтение",
    "module.writing": "Письмо",
    "module.cultural": "Культура",
    "module.yourMission": "Ваша миссия",
    "module.storyTranscript": "Транскрипт истории",
    "module.showTranslation": "Показать перевод",
    "module.learningHint": "Подсказка для обучения",
    "module.completeContinue": "Завершить и продолжить",
    "module.sectionComplete": "Раздел завершен",
    "module.quickActions": "Быстрые действия",
    "module.playModuleAudio": "Воспроизвести аудио модуля",
    "module.downloadPDF": "Скачать PDF",
    "module.joinDiscussion": "Присоединиться к обсуждению",
    "module.culturalSouvenir": "Культурный сувенир",
    "module.downloadSouvenir": "Скачать сувенир",
    "module.previousModule": "Предыдущий модуль",
    "module.markSectionComplete": "Отметить раздел как завершенный",
    "module.nextModule": "Следующий модуль",
    "module.learnEssential": "Изучите основную лексику для этого модуля",
    "module.noVocabulary": "Нет лексических элементов для этого модуля",
    "module.previousStory": "Предыдущий: История",
    "module.markAsComplete": "Отметить как завершенное",
    "module.nextGrammar": "Следующий: Грамматика",
    "module.masterGrammar": "Освойте грамматические структуры",
    "module.grammarRules": "Грамматические правила",
    "module.examples": "Примеры",
    "module.practiceExercises": "Упражнения для практики",
    "module.previousVocabulary": "Предыдущий: Лексика",
    "module.nextPronunciation": "Следующий: Произношение",
    "module.masterPronunciation": "Освойте правильное произношение",
    "module.focusAreas": "Области фокуса",
    "module.pronunciationExercises": "Упражнения на произношение",
    "module.minimalPairs": "Минимальные пары",
    "module.previousGrammar": "Предыдущий: Грамматика",
    "module.nextListening": "Следующий: Аудирование",
    "module.practiceUnderstanding": "Практикуйте понимание разговорного эстонского",
    "module.playAudioDialogue": "Воспроизвести аудио диалог",
    "module.listenCarefully": "Слушайте внимательно и следуйте",
    "module.listenToAudio": "Слушать аудио",
    "module.transcript": "Транскрипт",
    "module.comprehensionQuestions": "Вопросы на понимание",
    "module.previousPronunciation": "Предыдущий: Произношение",
    "module.nextSpeaking": "Следующий: Говорение",
    "module.practicePronunciation": "Практикуйте говорение на эстонском",
    "module.speakingExercises": "Упражнения на говорение",
    "module.prompt": "Задание:",
    "module.expectedResponse": "Ожидаемый ответ:",
    "module.startRecording": "Начать запись",
    "module.previousListening": "Предыдущий: Аудирование",
    "module.nextReading": "Следующий: Чтение",
    "module.readAndUnderstand": "Читайте и понимайте эстонские тексты",
    "module.readingText": "Текст для чтения",
    "module.previousSpeaking": "Предыдущий: Говорение",
    "module.nextWriting": "Следующий: Письмо",
    "module.writingPractice": "Практикуйте письмо на эстонском",
    "module.writingExercises": "Упражнения на письмо",
    "module.hints": "Подсказки:",
    "module.writeResponse": "Напишите ваш ответ здесь...",
    "module.submitWriting": "Отправить письменную работу",
    "module.previousReading": "Предыдущий: Чтение",
    "module.nextCulture": "Следующий: Культура",
    "module.culturalNote": "Откройте для себя эстонскую культуру и традиции",
    "module.digitalSouvenir": "Цифровой сувенир:",
    "module.previousWriting": "Предыдущий: Письмо",
    "module.congratulations": "Поздравляем!",
    "module.completedAllSections": "Вы завершили все разделы этого модуля",
    "module.takeFinalQuiz": "Пройти итоговый тест",

    // Progress page
    "progress.modulesCompleted": "Модулей завершено",
    "progress.ofTotal": "из",
    "progress.loadingProgress": "Загрузка вашего прогресса...",
    "progress.loginRequired": "Требуется вход",
    "progress.loginRequiredDesc": "Пожалуйста, войдите в систему, чтобы просмотреть ваш прогресс обучения.",
    "progress.title": "Ваш прогресс обучения",
    "progress.welcomeNewUser": "Начните ваше путешествие в изучении эстонского языка сегодня.",
    "progress.welcomeReturning": "Продолжайте в том же духе!",
    "progress.overallProgress": "Общий прогресс",
    "progress.completionRate": "процент завершения",
    "progress.studyTime": "Время обучения",
    "progress.totalHours": "всего часов",
    "progress.currentStreak": "Текущая серия",
    "progress.daysActive": "дней активности",
    "progress.overallCourseProgress": "Общий прогресс курса",
    "progress.modulesRemaining": "модулей осталось",
    "progress.nextMilestone": "Следующая веха",
    "progress.moduleProgress": "Прогресс модулей",
    "progress.progress": "Прогресс",
    "progress.review": "Повторить",
    "progress.continue": "Продолжить",
    "progress.start": "Начать",
    "progress.viewAllModules": "Посмотреть все {total} модулей",
    "progress.startLearning": "Начать обучение",
    "progress.continueLearning": "Продолжить обучение",
    "progress.beginJourney": "Начните ваше эстонское путешествие с модуля 1",
    "progress.pickUpWhereLeft": "Продолжите с того места, где остановились",
    "progress.startNow": "Начать сейчас",
    "progress.achievements": "Достижения",
    "progress.viewMilestones": "Просмотрите ваши учебные вехи и значки",
    "progress.viewAchievements": "Посмотреть достижения",
    "progress.detailedStats": "Подробная статистика",
    "progress.analyzePatterns": "Анализируйте ваши учебные паттерны и производительность",
    "progress.comingSoon": "Скоро",
    "progress.milestones": {
      firstModule: "Завершите ваш первый модуль!",
      fiveModules: "Достигните 5 модулей, чтобы разблокировать достижения!",
      tenModules: "Завершите 10 модулей, чтобы получить ваш первый сертификат!",
      twentyModules: "На полпути к мастерству - 20 модулей!",
      allModules: "Завершите все модули для получения финального сертификата!",
      mastered: "Поздравляем! Вы освоили эстонский язык!",
    },

    // Achievements page
    "achievements.title": "Достижения",
    "achievements.description": "Отслеживайте вехи обучения и разблокируйте значки",
    "achievements.all": "Все",
    "achievements.learning": "Обучение",
    "achievements.progress": "Прогресс",
    "achievements.social": "Социальные",
    "achievements.special": "Особые",
    "achievements.totalPoints": "Всего очков",
    "achievements.dayStreak": "Дней подряд",
    "achievements.modules": "Модулей",
    "achievements.nextAchievement": "Следующее достижение",
    "achievements.statistics": "Статистика",

    // Exam page
    "exam.title": "Итоговый экзамен",
    "exam.subtitle": "Проверьте ваши навыки эстонского языка",
    "exam.locked": "Экзамен заблокирован",
    "exam.lockedDesc": "Завершите {required} модулей, чтобы разблокировать итоговый экзамен",
    "exam.complete": "Экзамен завершен",
    "exam.results": "Ваши результаты",
    "exam.pointsEarned": "Заработанные очки",
    "exam.congratulations": "Поздравляем!",
    "exam.passed": "Вы успешно сдали экзамен по эстонскому языку!",
    "exam.failed": "Вам нужно 70% или выше для прохождения. Продолжайте учиться и попробуйте снова!",
    "exam.downloadCertificate": "Скачать сертификат",
    "exam.retakeExam": "Пересдать экзамен",
    "exam.viewProgress": "Посмотреть прогресс",
    "exam.instructions": "Инструкции к экзамену",
    "exam.totalPoints": "Всего очков",
    "exam.hours": "Часов",
    "exam.toPass": "Для прохождения",
    "exam.sections": "Разделов",
    "exam.startExam": "Начать экзамен",
    "exam.vocabulary": "Лексика (20 очков)",
    "exam.grammar": "Грамматика (20 очков)",
    "exam.pronunciation": "Произношение (10 очков)",
    "exam.listening": "Аудирование (15 очков)",
    "exam.reading": "Чтение (15 очков)",
    "exam.cultural": "Культурные знания (5 очков)",

    // Payment page
    "payment.title": "Обновиться до Премиум",
    "payment.subtitle": "Разблокируйте все модули и получите сертификат",
    "payment.backToModules": "Вернуться к модулям",
    "payment.moduleRequiresPremium": "требует доступа Премиум.",
    "payment.upgradeNow": "Обновитесь сейчас, чтобы продолжить обучение!",
    "payment.choosePlan": "Выберите ваш план",
    "payment.selectPlan": "Выберите план, который подходит вам лучше всего",
    "payment.paymentMethod": "Способ оплаты",
    "payment.choosePayment": "Выберите предпочитаемый способ оплаты",
    "payment.emailAddress": "Адрес электронной почты",
    "payment.emailPlaceholder": "Введите ваш адрес электронной почты",
    "payment.cardNumber": "Номер карты",
    "payment.cardPlaceholder": "1234 5678 9012 3456",
    "payment.expiryDate": "Срок действия",
    "payment.expiryPlaceholder": "ММ/ГГ",
    "payment.cvv": "CVV",
    "payment.cvvPlaceholder": "123",
    "payment.cardholderName": "Имя держателя карты",
    "payment.cardholderPlaceholder": "Полное имя на карте",
    "payment.orderSummary": "Сводка заказа",
    "payment.total": "Итого",
    "payment.acceptTerms": "Я принимаю",
    "payment.termsOfService": "Условия обслуживания",
    "payment.and": "и",
    "payment.privacyPolicy": "Политику конфиденциальности",
    "payment.processing": "Обработка...",
    "payment.completePayment": "Завершить платеж",
    "payment.securePayment": "Безопасное 256-битное SSL шифрование",
    "payment.emailRequired": "Требуется электронная почта",
    "payment.validEmail": "Пожалуйста, введите действительную электронную почту",
    "payment.cardRequired": "Требуется номер карты",
    "payment.validCard": "Пожалуйста, введите действительный номер карты",
    "payment.expiryRequired": "Требуется срок действия",
    "payment.validExpiry": "Пожалуйста, введите действительный срок действия (ММ/ГГ)",
    "payment.cvvRequired": "Требуется CVV",
    "payment.validCvv": "Пожалуйста, введите действительный CVV",
    "payment.nameRequired": "Требуется имя держателя карты",
    "payment.mustAcceptTerms": "Вы должны принять условия и положения",
    "payment.processingFailed": "Обработка платежа не удалась. Пожалуйста, попробуйте снова.",

    // Forgot Password page
    "forgotPassword.title": "Забыли пароль",
    "forgotPassword.resetPassword": "Сбросить пароль",
    "forgotPassword.enterEmail": "Введите ваш адрес электронной почты, и мы отправим вам ссылку для сброса",
    "forgotPassword.emailAddress": "Адрес электронной почты",
    "forgotPassword.enterEmailPlaceholder": "Введите ваш адрес электронной почты",
    "forgotPassword.sendResetEmail": "Отправить письмо для сброса",
    "forgotPassword.sendingResetEmail": "Отправка письма для сброса...",
    "forgotPassword.backToLogin": "Вернуться к входу",
    "forgotPassword.needHelp": "Нужна помощь?",
    "forgotPassword.helpText1": "Убедитесь, что вы вводите правильный адрес электронной почты",
    "forgotPassword.helpText2": "Проверьте папку спама, если не видите письмо",
    "forgotPassword.helpText3": "Ссылки для сброса истекают через 1 час для безопасности",
    "forgotPassword.helpText4": "Обратитесь в поддержку, если проблемы продолжаются",
    "forgotPassword.demoText": "Это демо. Реальные письма отправляться не будут.",
    "forgotPassword.pleaseEnterEmail": "Пожалуйста, введите ваш адрес электронной почты",
    "forgotPassword.pleaseEnterValidEmail": "Пожалуйста, введите действительный адрес электронной почты",
    "forgotPassword.failedToSend": "Не удалось отправить письмо для сброса. Пожалуйста, попробуйте снова.",
    "forgotPassword.resetEmailSent": "Письмо для сброса отправлено",
    "forgotPassword.checkInbox": "Пожалуйста, проверьте ваш почтовый ящик для инструкций по сбросу",
    "forgotPassword.sentTo": "Письмо отправлено на:",
    "forgotPassword.important": "Важно:",
    "forgotPassword.checkSpam": "Проверьте папку спама/нежелательной почты",
    "forgotPassword.linkExpires": "Ссылка истекает через 1 час",
    "forgotPassword.ignoreIfNotRequested": "Игнорируйте это письмо, если вы его не запрашивали",
    "forgotPassword.sendAnotherEmail": "Отправить другое письмо",
    "forgotPassword.stillTrouble": "Все еще проблемы?",
    "forgotPassword.demoMode": "В демо режиме ссылки для сброса пароля ведут на /reset-password?token=valid123",

    // Terms page
    "terms.backToLogin": "Вернуться к входу",
    "terms.title": "Условия обслуживания",
    "terms.lastUpdated": "Последнее обновление: декабрь 2024",
    "terms.returnToLogin": "Вернуться к входу",

    // Privacy page
    "privacy.backToLogin": "Вернуться к входу",
    "privacy.title": "Политика конфиденциальности",
    "privacy.lastUpdated": "Последнее обновление: декабрь 2024",
    "privacy.returnToLogin": "Вернуться к входу",

    // Map section translations
    "map.yourEstonianAdventure": "Ваше эстонское приключение",
    "map.trackProgress": "Отслеживайте ваш прогресс по красивым местам Эстонии и отмечайте ваши достижения.",
    "map.exploreDestinations":
      "Исследуйте красивые места Эстонии. Модули 1-3 бесплатны! Войдите, чтобы разблокировать все модули и сохранить прогресс.",
    "map.exploreFreeDemo": "🗺️ Исследуйте Эстонию - Бесплатная демоверсия",
    "map.freeModulesDesc":
      "Модули 1-3 полностью бесплатны! Исследуйте Таллинн, Тарту и Сааремаа. Войдите, чтобы разблокировать все {count} направлений и отслеживать прогресс.",
    "map.loginToUnlockAll": "Войти, чтобы разблокировать все",
    "map.destinationsVisited": "Посещенных мест",
    "map.freeDestinations": "Бесплатных мест",
    "map.overallProgress": "Общий прогресс",
    "map.hoursContent": "Часов контента",
    "map.adventureMap": "Карта приключений Эстонии ({count} направлений)",
    "map.clickDestinations": "Нажмите на места, чтобы увидеть ваш прогресс и продолжить путешествие",
    "map.freeToExplore": "Модули 1-3 бесплатны для изучения! Войдите, чтобы разблокировать все места.",
    "map.loadingMap": "Загрузка карты...",
    "map.mapLegend": "Легенда карты",
    "map.completed": "Завершено",
    "map.freeAccess": "Бесплатный доступ",
    "map.available": "Доступно",
    "map.locked": "Заблокировано",
    "map.loginToUnlock": "Войти для разблокировки",
    "map.completePrevious": "Завершите предыдущие модули для разблокировки",
    "map.reviewModule": "Повторить модуль",
    "map.continue": "Продолжить",
    "map.startFreeModule": "Начать бесплатный модуль",
    "map.startModule": "Начать модуль",

    // Common
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успех",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.view": "Просмотр",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.previous": "Предыдущий",
    "common.submit": "Отправить",
    "common.close": "Закрыть",
    "common.loginToContinue": "Войти для продолжения",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("EN")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "EN" || savedLanguage === "RU")) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const t = (key: string): string => {
    return translations[language][key] || translations.EN[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
